title: DOCoMETRe
email: frank.buloup@univ-amu.fr
description: >- # this means to ignore newlines until "baseurl:"
  Data acquisition and processing software
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
